version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "shopper"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  migrations:
    image: node:18
    command:
      [
        "sh",
        "-c",
        "yarn  && yarn build && ./node_modules/.bin/typeorm migration:run -d dist/infrastructure/database/database.js",
      ]
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
